-- ============================================================================
-- 0012_family_notifications.sql
-- NO-OP
--
-- The repository's previous 0012 file was a duplicate of the 0011 messaging
-- migration rather than a notification migration.  0011 owns the messaging
-- objects.  This migration intentionally does nothing so migration history
-- remains stable and no production objects are dropped or recreated.
-- ============================================================================
